config/routes.rb
Myapp::Application.routes.draw do

  devise_for :users

  get "/" => "home#index"
  get "dashboard" => "home#dashboard"
  resources :incidents do
    collection do
      get :reports
      get :generate_report
    end
  end

  

end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-inverse navbar-bottom" role="navigation"
     style="color: #fff; font-family: 'Patrick Hand'; font-size: 18px; background-color: #333333">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-4">
        Left
      </div>
      <div class="col-md-4">
        Middle
      </div>
      <div class="col-md-4">
        Right
      </div>
    </div>
    <div class="clearfix"></div>


  </div>


</nav>

<p class="navbar-text pull-right">
  <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>

app/views/layouts/_header.html.erb
<div class="col-md-12" >
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation"
       >
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
      </button>
      <a class="navbar-brand header-brand" href="/">Telstra</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>

        </li>
        <li>
          <%= link_to "Upload Files", new_incident_path %>
        </li>
        <li>
          <%= link_to "Server Inventory", reports_incidents_path %>
        </li>
        <li>
          <%= link_to "Dashboard", dashboard_path %>
        </li>
      </ul>

      <p class="nav navbar-text navbar-right" style="width:130px">

        <% if user_signed_in? %>
            <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login ", new_user_session_path, :class => 'navbar-link'  %>

        <% end %>
        <!--<li class="dropdown">-->
          <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown">User Name<strong class="caret"></strong></a>-->
          <!--<ul class="dropdown-menu">-->
            <!--<li>-->
              <!--<a href="#">Profile</a>-->
            <!--</li>-->
            <!--<li>-->
              <!--<a href="#">Logout</a>-->
            <!--</li>-->
          <!--</ul>-->
        <!--</li>-->
        <!--<li>-->
          <!--<a href="/login">Login</a>-->
        <!--</li>-->

      </p>
    </div>

  </nav>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Telstra</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>




<div class="container-fluid" style="background-color: transparent">
  <div class="row">
    <%= render :partial => 'layouts/header' %>
  </div>
  <div class="clearfix"></div>
  <div class="row" style="margin-top: 50px">
    <div class="container-fluid" style="background-color: transparent">
      <% if notice %>
          <p class="alert alert-success fade in"><%= notice %></p>
      <% end %>
      <% if alert %>
          <p class="alert alert-danger fade in"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </div>
  <div class="clearfix"></div>
  <img src="/assets/loading-x.gif" id="loading-indicator" style="display:none" />
  <!--<div class="row">-->
    <!--<%= render :partial => 'layouts/footer' %>-->
  <!--</div>-->
</div>
</body>
</html>